### PR TITLE
[dotnet core] build for linux-musl-arm64

### PR DESCRIPTION
**Pull request by bfren**
See #1173

### CODE REVIEW

**Comment by ektrah** [comment]
Nice work 😃 

The artifact (libsodium.so) also needs to be added to [libsodium.pkgproj](https://github.com/jedisct1/libsodium/blob/master/packaging/dotnet-core/libsodium.pkgproj) so it gets included in the NuGet package.

/cc @SeanMollet @enclave-alistair

**Comment by bfren** [comment]
Done - I think!

**Comment by ektrah** [comment]
libsodium.pkgproj looks good to me. While you're at it, you could also increment the version number in the same file.

Now someone needs to go ahead and test if the NuGet package actually works on their musl arm64 machine 😊

**Comment by SeanMollet** [comment]
@ektrah  That can be tested in a docker container. I might have some time later this week to build a proper test script for it.

**Comment by bfren** [comment]
> libsodium.pkgproj looks good to me. While you're at it, you could also increment the version number in the same file.

Happy to bump the version - to 1.0.19.0?

**Comment by bfren** [comment]
@SeanMollet I'm happy to help with writing test scripts - I presume I need to build the package locally to test it?  The CI process doesn't appear to publish it anywhere as far as I can tell.

**Comment by bfren** [comment]
Is there anything more I can do to help get this finalised and merged?

**Comment by MichalPetryka** [comment]
Could `linux-musl-arm` and `linux-s390x` be handled too?

**Comment by ektrah** [comment]
@MichalPetryka, [.NET doesn’t run on s390x](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md). (Note that this particular PR is about the packaging of libsodium for .NET, not libsodium in general.)

**Comment by MichalPetryka** [comment]
> @MichalPetryka, [.NET doesn’t run on s390x](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md). (Note that this particular PR is about the packaging of libsodium for .NET, not libsodium in general.)

It does with community builds, fedora package repository does provide s390x builds of it.

**Comment by bfren** [comment]
I'd be happy to do what I did for arm64 to add an arm build - would the maintainers prefer another PR for that?  The issue now is testing though, which I'm happy to help with if I can, and if someone wants to give me a steer.

**Pull request merged**
