### PR TITLE
Fixes #328

### LINKED ISSUE #328: crypto_sign_edwards25519sha512batch_open doesn't return original message
This appears to be a trivial offset error in the function.

### PR DESCRIPTION
**Pull request by Fraser999**
This adds a basic test which exposes the issue and also has a fix for the bug.

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks! The offset was fixed, but this obsolete function will go away, and tests are only for documented functions.

**Comment by Fraser999** [comment]
OK - thanks.  Will you be updating the prebuilt binaries with this fix?

**Comment by jedisct1** [comment]
prebuilt binaries follow the stable branch, so yes. They already include this.

**Comment by Fraser999** [comment]
It looks like libsodium-1.0.7.tar.gz hasn't been updated.

**Comment by jedisct1** [comment]
No, that one will not change.

**Pull request closed without merging**
