### PR TITLE
crypto_box_curve25519xchacha20poly1305_seal emscripten sumo exports

### PR DESCRIPTION
**Pull request by buu700**
Noticed this was missing in https://github.com/jedisct1/libsodium/commit/ccb842f4884aa8917dcbba79509a349f8c475b3c and that the latest release notes said that sumo would include all symbols, so figured it was probably just an oversight. (We're using this as part of a custom build of libsodium.js.)

### CODE REVIEW

**Comment by jedisct1** [comment]
libsodium 1.0.13 hasn't been released yet!

**Comment by jedisct1** [comment]
Anyway, this is it :)

**Comment by jedisct1** [comment]
s/it/in/

**Comment by jedisct1** [comment]
Now the libsodium.js wrappers have to be updated...

**Comment by buu700** [comment]
Oh, lol. And nice, thanks again for adding this!

**Comment by buu700** [comment]
@jedisct1, not sure what the problem could be, but for some reason when I build with libsodium master instead of my fork `crypto_box_curve25519xchacha20poly1305_seal` is undefined. I notice that https://github.com/jedisct1/libsodium/commit/e325b6d76b670544b47f8b2fe5871bd408b119a6 added a comma to the start of `EXPORTED_FUNCTIONS_SUMO` that hadn't been there previously; could that be related?

If it's helpful, [here's my broken sumo build](https://gist.github.com/buu700/305e7efd564f687973b3261fb155111c).

**Comment by jedisct1** [comment]
The leading coma shouldn't help :)

Should be fixed now!

Thanks!

**Comment by buu700** [comment]
Awesome, thanks!

**Pull request closed without merging**
