### PR TITLE
Including linux-musl-arm package

### PR DESCRIPTION
**Pull request by bfren**
I've included the missing package and bumped the version to 1.0.18.4

### CODE REVIEW

**Comment by bfren** [comment]
Fixes [this problem](https://github.com/jedisct1/libsodium/issues/1233#issuecomment-1345557009).

**Comment by jedisct1** [comment]
Doesn't `packaging/nuget/package.config` need to be updated as well?

**Comment by jedisct1** [comment]
Congrats for PR #1234 :)

**Comment by ektrah** [comment]
`packaging/dotnet-core` and `packaging/nuget` are unrelated, so keeping them in sync is not necessary. The former is used for building the [libsodium](https://www.nuget.org/packages/libsodium) NuGet package that contains pre-compiled binaries for .NET bindings. The latter builds the [libsodium_vc120](https://www.nuget.org/packages/libsodium_vc120) NuGet package that contains pre-compiled binaries for Visual C++ projects (not updated since 2017).

**Comment by jedisct1** [comment]
Thanks!

Can the latter be safely removed, or is it useful?

**Pull request merged**
