### PR TITLE
Introduce C++Builder compatibility

### PR DESCRIPTION
**Pull request by jcolli44**
Add new preprocessor directives to allow libsodium to be easily
built in C++Builder.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi, and thanks for these changes!

How do you compile and run the test suite using C++Builder?

**Comment by jcolli44** [comment]
The way I did it was create a console application for each test under a group project. Then I built all console applications, and copied the generated .exe's to /test/default and wrote a batch script to execute each one and print failed if process returned 1, like wintest.bat does.

**Comment by jedisct1** [comment]
Thanks!

I'm not very familiar with Borland C++. Just downloaded it, and I'm stuck trying to compile a Hello World :)

Can you add the missing pieces such as the Makefile to build the library and the required scripts to run the tests?

**Comment by jcolli44** [comment]
Instead of creating a makefile, we ended up creating a bunch of project files (one for the library, and one per test executable) to build libsodium and its test suite in C++ Builder. Since there is already a builds/msvc, we could create a builds/cbuilder directory and put the project files in there.

**Comment by jedisct1** [comment]
Thanks!

The changes have been merged!

But supporting C++Builder seems like a lot of work and the compiler is not free. So don't consider this compiler as supported. New versions might break.

**Comment by jcolli44** [comment]
Ok, thank you for merging our changes!

**Pull request merged**
