### PR TITLE
Added capability of setting the initial block counter value for XSalsa20.

### PR DESCRIPTION
**Pull request by Cyberunner23**
Second try... Made a small typo that broke the tests... and... stuff...

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

The `_ic` functions only make sense when block ciphers are used in counter mode, which is what salsa20 and chacha20 are in disguise.

But the `crypto_stream` interface should remain generic enough not to assume that the underlying stream cipher is using a counter.

For this reason, if initializing the counter for xsalsa20 is being added, this should be only exposed within the `crypto_stream_xsalsa20` namespace.

**Comment by jedisct1** [comment]
My bad, I got confused by the definition in `api.h`.

Looks good.

**Comment by Cyberunner23** [comment]
Thanks for the heads up! Want me to clean it up a little?

**Comment by jedisct1** [comment]
It's been merged in a1b3da7dd990a97e0b9e8fe2933b5f2806186c2d

Last thing that requires an update is the documentation.

**Pull request closed without merging**
