### PR TITLE
Fix CPU feature detection crash on VS 2010 32-bit /O2

### PR DESCRIPTION
**Pull request by etodd**
This is a crash in a very specific build configuration, where the optimizer put the cpu_features pointer in eax, and then eax got blown away by the feature detection asm. Turning off optimizations for this function solved the problem.

### CODE REVIEW

**Comment by jedisct1** [comment]
That looks like a kludgy and unreliable workaround we can't rely on. 

We should rather push/pop `%eax` and `%ecx` in the assembly code.

**Comment by jedisct1** [comment]
Maybe `%edx` as well.

**Comment by jedisct1** [comment]
Quoting: https://msdn.microsoft.com/en-us/library/k1a8ss06.aspx

> When using __asm to write assembly language in C/C++ functions, you don't need to preserve the EAX, EBX, ECX, EDX, ESI, or EDI registers.

That doesn't match what you report. Or was that guarantee introduced after VS2010?

**Comment by jedisct1** [comment]
Actually, Microsoft wrote the same thing about VS2010: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/k1a8ss06(v=vs.100)

**Comment by jedisct1** [comment]
Can you still try to save the GPRs, and see if that fixes the issue you are seeing?

**Comment by etodd** [comment]
To be more clear, this is the specific #ifdef activated by this build configuration:

    # elif defined(_MSC_VER) && defined(_M_IX86)

**Comment by jedisct1** [comment]
The registers being changed by `xgetbv` is expected, but the compiler should save and restore the ones holding values used both before and after the `__asm` block.

 So, either a compiler bug, or a different root cause.

Can you add

```asm
push eax
push ecx
push edx
```

to the beginning of the block, and

```
pop edx
pop ecx
pop eax
```

to the end?

**Comment by etodd** [comment]
That also worked. Pretty weird stuff. Added those changes here.

**Comment by jedisct1** [comment]
Added in cfb0f94704841f943a5a11d9e335da409c55d58a (with correct indentation and a comment to justify this).

Thanks!

**Pull request closed without merging**
