### PR TITLE
Add testcases and expected output files

### PR DESCRIPTION
**Pull request by arindam-8**
This is the PR following the [discussion](https://github.com/jedisct1/libsodium/discussions/1273) on the libsodium repository's discussion board. It adds 3 testcases extracted from 2 different libsodium clients: [dovecot](https://github.com/dovecot/core) and [blobcrypt](https://github.com/jedisct1/blobcrypt).

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi @arindam-8 !

And thanks for these tests!

But I'm a little bit confused. They don't seem to test anything that is not already present in existing tests.

They just evaluate `crypto_pwhash` and `crypto_generichash` with fixed parameters, but the `pwhash_argon2*` and `generichash*` tests already do it, along with other parameters.

A more interesting thing to do would be to run the tests, look at code coverage, and try to write tests that exercise code that was not previously covered.

**Comment by pengwinsurf** [comment]
Hi @jedisct1,

I am working with @arindam-8 on generating those test cases for libsodium from clients using the library.

Thank you for the quick response on the PR, really appreciate it. Also thank you for the feedback.

I did some coverage measurement on for those test cases and I can confirm I see an increase in coverage. The way I did the testing is I built the latest stable release with coverage and ran `make check` to get the baseline coverage. Following that I ran the test cases and collected coverage using lcov. 

The baseline I got running `make check` was 
```
Lines: 12669/14466 (87.6%) , Functions: 986/1067 (92.4%) , Branches: 3220/5155 (62.5%) 
```

After running the test cases the coverage shows the following

```
Lines: 12781/14466 (88.4%), Functions: 992/1067 (93%), Branches: 3267/5155 (63.4%)
```

The additional coverage is in 3 files `argon2-fill-block-ref.c ` ,  `blamka-round-ref.h` and `blake2b-compress-ref.c`

Thats 88 lines in `argon2-fill-block-ref.c`, 4 lines in `blamka-round-ref.h` and 20 lines in `blake2b-compress-ref.c`. 

Hope this information helps. 

One last thing, I wanted to ask is regarding the CI tests. It seems that at the moment, running the CI requires some authorisation to run all of the tests? Is there an easier way to run all the CI tests locally for a faster turn around ? 

Thanks!

**Comment by arindam-8** [comment]
Hey,

Is there anything else that would help clarify this PR further? 

Thanks
Arindam

**Comment by pengwinsurf** [comment]
Hi @jedisct1,

Is there any chance you could comment on this PR given the information regarding coverage etc ?

**Comment by nanis94** [comment]
arindam-8:test vakaları master

**Comment by jedisct1** [comment]
These tests don't test anything that is not already exercised by the current test suite.

**Pull request closed without merging**
