### PR TITLE
Add constant-time Base64 encoding and decoding

### PR DESCRIPTION
**Pull request by entrope**
This should address #438.

I based this on the C++ version by Sc00bz (linked in #438), but took the liberty of handling padding in constant time by reducing b64_len.

This code assumes two's complement representation of signed integers; is that worth avoiding?

### CODE REVIEW

**Comment by jedisct1** [comment]
To be honest, I'm a bit reluctant to include functions for base64 encoding/decoding.

base64 is a mess, with no less than [15 common, but incompatible variants](https://en.wikipedia.org/wiki/Base64#Variants_summary_table).

As an example, a base64 codec is [already present in libsodium](https://github.com/jedisct1/libsodium/blob/c229663acf6083867b8df35aeb8647e6d4db1270/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c#L53).

Can we remove it and replace it with your implementation of a given variant? Unfortunately not, because this is not the same variant (no padding).

Would anyone use your implementation or the existing one to pass around signatures in URLs? No, because another variant would be a better fit.

Base64 is less efficient than Base85. Base64 is not human-readable as Base58.

Essentially, I don't see any valid reason to use Base64. Ever.

**Comment by entrope** [comment]
I am not sure what you mean by "this is not the same variant".  The decoder in this PR should handle padding being present and padding not being present.  The encoder here does not append padding, but could (at least when 

The variants listed on Wikipedia vary by the last two characters used; by whether padding is mandatory, optional, or prohibited; line length; how to handle non-Base64 characters; and checksum.  (The non-Base64 handling and checksum are only really different for one variant in each case.)  I think it would be straightforward to parameterize this while preserving the constant-time aspect by passing a string that specifies the last two Base64 digits, the padding character, and perhaps how to handle whitespace and/or non-Base64 characters.

Base85 also has a plethora of variants, some of which leak content by design (the "z" and "y" abbreviations for btoa and Ascii85) and need escapes for many digits, and others (Z85 and RFC1924/git version) that use a lot of non-contiguous ranges that slow down constant-time conversion.  RFC1924 works on 128-bit chunks; git uses the same digits, but works on 32-bit chunks.

Base58 also has a number of variants, all of which use lots of non-contiguous ranges, and does not have any standard for how many bytes to convert per chunk.  (41 bits in 7 Base58 digits?  64 bits in 11 Base58 digits?  Something else?)

All of the text formats are unhappy mediums: base16 is inefficient, base58 is inefficient and awkward except for human I/O, base64 is widely used for key and certificate exchange but has a lot of variants, base85 has several variants that are more fundamentally different than the base64 variants.

If you want to close this, I have no great objection, but it might be useful to mention your concerns in issue #438 for the next person to come along who is looking to help out.

**Comment by jedisct1** [comment]
This is a sad state of affairs. There are many encoding systems and many variants, each of them being useful.

Ideally, we would want to support them all, but being a BaseXX conversion library is not really the purpose of libsodium.

Still, having great, constant-implementations of these would be very useful, but I think this would be a project on its own.

**Comment by jedisct1** [comment]
Of course we could just implement one system/variant. This is what PHP does in its standard library. 

But if you look at the user comments in that function documentation, you will notice many code snippets performing additional substitutions (which would defeat the point of a constant-time implementation) to construct different variants.

So we can't really offer just one variant, or the same thing is going to happen.

**Comment by paragonie-scott** [comment]
> base64 is a mess, with no less than 15 common, but incompatible variants.

But it has [an RFC](https://tools.ietf.org/html/rfc4648). If this weren't a `wontfix`, I would recommend only implementing the RFC 4648 variants.

> Essentially, I don't see any valid reason to use Base64. Ever.

The only reason to use it is because Base-N (where N is an even multiple of 2) is easy to implement in constant-time.

> Of course we could just implement one system/variant. This is what PHP does in its standard library.

They also refused to make their implementation constant time, fearing FUD about performance concerns, so I [took and expanded Sc00bz's code](https://github.com/paragonie/constant_time_encoding). (PHP didn't ship base32 either, so people who use this library get that too.)

Not shipping more encoding functions is probably the right choice.

**Comment by jedisct1** [comment]
That RFC predates the web; I'm not sure that it is still relevant today.

If we have to implement one, picking one that doesn't require URL encoding would probably be a better choice.

**Comment by BurningEnlightenment** [comment]
> That RFC predates the web; I'm not sure that it is still relevant today.

I always thought that [RFC4648](https://tools.ietf.org/html/rfc4648) would be _the_ base64 standard :confused: and at least the creator/maintainer of a _very_ fast base64 codec implementation thinks like this, too: https://github.com/aklomp/base64/issues/27#issuecomment-255472737 (I know that this is not representative in any way, but your debate reminded me of it)

> Still, having great, constant-implementations of these would be very useful, but I think this would be a project on its own.

I second this; base64 is a data encoding and not a crypto algorithm which therefore doesn't belong to a crypto library, but to some external codec library.

Just my 2ct.

**Pull request closed without merging**
