### PR TITLE
Port libsodium to SGX

### PR DESCRIPTION
**Pull request by rbost**
PR corresponding to Issue #685.
I got it working on an Ubuntu 16 LTS VM in simulation mode (I do not have access to an Intel chip with SGX enabled, and could not test it in hardware mode). 

I was not able to figure out where to add the documentation related to the changes, but once I am told, I would be happy to make the changes.

### CODE REVIEW

**Comment by rbost** [comment]
@Moschn Sorry about that, I left a typo in the autoconf file ... (see commit b85df91).

This being fixed, I was able to run ./autogen.sh &&  ./configure --enable-sgx && make -j && make check without any issue. It would be great if you could test the code again :)

**Comment by Moschn** [comment]
@rbost I tried it and indeed it compiles now. But all tests fail with the error `Illegal Instruction`. Some lines from the output:
```
../../build-aux/test-driver: line 107: 19285 Illegal instruction     (core dumped) "$@" > $log_file 2>&1
FAIL: aead_aes256gcm
../../build-aux/test-driver: line 107: 19292 Illegal instruction     (core dumped) "$@" > $log_file 2>&1
FAIL: aead_chacha20poly1305
../../build-aux/test-driver: line 107: 19299 Illegal instruction     (core dumped) "$@" > $log_file 2>&1
FAIL: aead_xchacha20poly1305
```
I can also provide you with the core dumps if you need them. 

Intel SGX disallows [some instructions](https://software.intel.com/en-us/node/703005) inside an enclave. I think it might be possible to disable some of these instructions with `./configure` but I have not experimented with this.

**Comment by rbost** [comment]
@Moschn This is great news: somethings happens!

It would be great if you could send me the core dumps.

I knew about the forbidden instructions, and genuinely thought I did not use them. My hope is that this is coming from the SGX-only code I wrote for the tests. If it comes from the inners of libsodium, this is going to be a lot less fun ...

**Comment by Moschn** [comment]
Sent it to you via email

**Comment by rbost** [comment]
@Moschn Unfortunately, I could not use the core dumps you sent me in a very useful way. However, after some thinking, and staring at the code, I realized that I did not remove the calls to sodium_malloc (and sodium_free) in the test code, which would create SIGILL (on a syscall). So I did change that in 41d65f88370fc171ccf7134d02c4e46ad08fe04f.

Also, in 9f3d485859f796428b7a153caa3d044ebd125551, I added some more logging to exactly see more precisely where the code fails without relying on a debugger.

Again, some testing from your side would be great!

**Comment by Moschn** [comment]
@rbost I still get the same errors:
```
../../build-aux/test-driver: line 107:  9944 Illegal instruction     (core dumped) "$@" > $log_file 2>&1
FAIL: aead_aes256gcm
```

**Comment by rbost** [comment]
@Moschn :( I will take a last look at the code to see what happens, but I am not sure I will find anything else. And I don't want to bother you too much.
So unless someone else debugs it, I will have to get my hands on a machine with SGX to get further.
Thanks a lot for your help anyway!!

**Comment by jedisct1** [comment]
This is probably not going to happen.

I don't have the required hardware to test this, this looks complicated to install on Linux and impossible elsewhere, I don't have any use case for this, this branch is unmaintained, CI cannot be used to test this either. If there is any interest in this, it should better be maintained independently.

**Pull request closed without merging**
