### PR TITLE
Added Catalyst Support

### PR DESCRIPTION
**Pull request by kappes**
Added Catalyst target to dist-build/iOS.sh, removed sim64 target b/c obsolete.

### CODE REVIEW

**Comment by jedisct1** [comment]
Did you test this?

Doesn't that break the simulator?

**Comment by jedisct1** [comment]
Can you move these changes back to where the `x86_64 simulator` building part was, so that the changes are more readable?

**Comment by kappes** [comment]
I'm working on a swift lib. Xcode 11 test target seem to need Catalyst support and that's working now as well as the sim. Seems like the Catalyst build replaces the x86_64.

**Comment by jedisct1** [comment]
Thanks!

**Pull request closed without merging**
