### PR TITLE
aegis256: Support mac verification when m is NULL

### PR DESCRIPTION
**Pull request by angt**
Signed-off-by: Adrien Gallouët <adrien@gallouet.fr>

### CODE REVIEW

**Comment by angt** [comment]
I have a commit without the store, tell me if you really want it :)

**Comment by jedisct1** [comment]
Don't speculate, just profile.

**Comment by angt** [comment]
`gcc` and `clang` are amazing 😲 

```$ cat compilos-are-crazy.sh
diff aegis256-store.c aegis256-nostore.c
for cc in gcc clang; do
	rm -rf *.[ios]
	echo "ASM DIFF for $cc"
	$cc -O2 -save-temps -c aegis256-store.c
	$cc -O2 -save-temps -c aegis256-nostore.c
	diff aegis256-store.s aegis256-nostore.s
done
$ sh compilos-are-crazy.sh
57c57
<     _mm_storeu_si128((__m128i *)dst, tmp);
---
>     //_mm_storeu_si128((__m128i *)dst, tmp);
ASM DIFF for gcc
1c1
< 	.file	"aegis256-store.c"
---
> 	.file	"aegis256-nostore.c"
164c164
< # 114 "aegis256-store.c" 1
---
> # 114 "aegis256-nostore.c" 1
ASM DIFF for clang
2c2
< 	.file	"aegis256-store.c"
---
> 	.file	"aegis256-nostore.c"
````

**Comment by jedisct1** [comment]
Hahaha, nice!

**Pull request merged**
